version: "3"
services:
  postgres:
    hostname: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/

  localstack:
    image: localstack/localstack:0.14.3
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    volumes:
      - './scripts:/docker-entrypoint-initaws.d'
      - './data:/s3/data'

volumes:
  database-data:
    driver: local
